'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  cycleLanguage: () => void;
}

const translations = {
  en: {
    // Home page
    'home.title': 'Baddi Health',
    'home.greeting': 'Hello, Rajesh Kumar',
    'home.physicalAppointment': 'Physical Appointment',
    'home.atHospital': 'At Hospital',
    'home.videoConsult': 'Video Consult',
    'home.connectIn5Sec': 'Connect in 5 sec',
    'home.medicines': 'Medicines',
    'home.pharmacyDelivery': 'Pharmacy Delivery',
    'home.labTests': 'Lab Tests',
    'home.homeCollection': 'Home Collection',
    'home.surgeries': 'Surgeries',
    'home.bookProcedure': 'Book Procedure',
    'home.findDoctor': 'Find a Doctor for your Health Problem',
    'home.generalPhysician': 'General Physician',
    'home.skinHair': 'Skin & Hair',
    'home.womensHealth': 'Women\'s Health',
    'home.dentalCare': 'Dental Care',
    'home.childSpecialist': 'Child Specialist',
    'home.ent': 'Ear, Nose, Throat',
    'home.mentalWellness': 'Mental Wellness',
    'home.more': '20+ more',
    'home.askHealthAI': 'Ask Health AI',
    'home.free': 'FREE',
    'home.queriesResolved': '20000+ health queries resolved in last month',
    'home.emergency': 'Emergency',
    'home.call108': 'Call 108',
    'home.pharmacy': 'Pharmacy',
    'home.checkAvailability': 'Check Availability',
    
    // Common
    'common.home': 'Home',
    'common.appointments': 'Appointments',
    'common.records': 'Records',
    'common.profile': 'Profile',
    'common.search': 'Search',
    'common.book': 'Book',
    'common.cancel': 'Cancel',
    'common.reschedule': 'Reschedule',
    'common.viewDetails': 'View Details',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.loading': 'Loading...',
    'common.logout': 'Logout',
    'common.quickActions': 'Quick Actions',
    'common.talkToAgent': 'Talk to Agent',
    'common.videoConsult': 'Video Consult',
    'common.callInProgress': 'Call in Progress',
    'common.connectingAgent': 'Connecting to healthcare agent...',
    'common.consultationRecorded': 'Your consultation will be automatically recorded',
    'common.cancelCall': 'Cancel Call',
    'common.hello': 'Hello',
    'common.user': 'User',
    'common.baddiHimachal': 'Baddi, Himachal',
    'common.sync': 'Sync',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.allRecordsSynced': 'All records are synced',
    'common.loadingRecords': 'Loading records...',
    'common.noRecordsFound': 'No records found',
    'common.noHealthRecordsYet': "You don't have any health records yet",
    'common.noRecordsOfType': 'No {type} records',
    'common.viewAllDetails': 'View All Details',
    'common.active': 'Active',
    'common.scheduled': 'scheduled',
    'common.completed': 'completed',
    'common.video': 'Video',
    'common.aiAssistant': 'AI Assistant',
    'common.addNewRecord': 'Add New Record',
    'common.uploadDocumentNote': 'Upload documents, add notes, or record new health information',
    'common.uploadDocument': '📄 Upload Document',
    'common.addNote': '📝 Add Note',
    'common.viewUpcoming': 'View upcoming',
    'common.checkAvailability': 'Check availability',
    'common.category': 'Category',
    'common.offlineMode': 'Offline Mode',
    'common.offlineModeDescription': "You are viewing cached records. New records will be saved locally and synced when you're back online.",
    'common.consultation': 'Consultation',
    'common.aiAnalysis': 'AI Analysis',
    'common.prescription': 'Prescription',
    'common.labTest': 'Lab Test',
    'common.vaccination': 'Vaccination',
    'common.patientReported': 'Patient reported having fever and throat pain and was advised to consult a doctor online.',
    'common.routineCheckup': 'Routine health checkup, blood pressure normal, weight stable',
    'common.bloodSugar': 'Fasting blood sugar: 95 mg/dL (Normal)',
    'common.medicationPrescribed': 'Paracetamol 500mg - 3 times daily for 3 days',
    'common.followUp': 'Follow-up for blood pressure medication',
    'common.noSummaryAvailable': 'No summary available',
    'common.consultationDescription': 'Patient reported having fever and throat pain and was advised to consult a doctor online.',
    'common.routineCheckupDescription': 'Routine health checkup, blood pressure normal, weight stable',
    'common.bloodSugarDescription': 'Fasting blood sugar: 95 mg/dL (Normal)',
    'common.medicationDescription': 'Paracetamol 500mg - 3 times daily for 3 days',
    'common.followUpDescription': 'Follow-up for blood pressure medication',
    'common.generalHealthCheckup': 'General Health Checkup',
    'common.bloodSugarTest': 'Blood Sugar Test',
    'common.medicationForFever': 'Medication for Fever',
    'common.followUpAppointment': 'Follow-up Appointment',
    'common.callRegistered': 'Call Registered',
    'common.awaitingDoctorResponse': 'Awaiting Doctor Response',
    'common.callCompleted': 'Call completed! Your consultation has been registered.',
    'common.agentCall': 'Agent Call',
    'common.callInProgress': 'Call in Progress',
    'common.connectingAgent': 'Connecting to healthcare agent...',
    'common.consultationRecorded': 'Your consultation will be automatically recorded',
    'common.cancelCall': 'Cancel Call',
    
    // Appointments
    'appointments.title': 'Appointments',
    'appointments.upcoming': 'Upcoming',
    'appointments.completed': 'Completed',
    'appointments.cancelled': 'Cancelled',
    'appointments.all': 'All',
    'appointments.pending': 'Pending',
    'appointments.confirmed': 'Confirmed',
    'appointments.noAppointments': 'No appointments',
    'appointments.noAppointmentsDescription': "You don't have any appointments yet",
    'appointments.bookNew': 'Book New Appointment',
    'appointments.upcomingReminder': 'Upcoming Appointment',
    
    // Profile
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.medicalInfo': 'Medical Information',
    'profile.fullName': 'Full Name',
    'profile.age': 'Age',
    'profile.phoneNumber': 'Phone Number',
    'profile.location': 'Location',
    'profile.bloodGroup': 'Blood Group',
    'profile.allergies': 'Allergies',
    'profile.medicalConditions': 'Medical Conditions',
    'profile.emergencyContact': 'Emergency Contact',
    'profile.settings': 'Settings',
    'profile.notifications': 'Notifications',
    'profile.language': 'Language',
    'profile.privacySecurity': 'Privacy & Security',
    'profile.offlineMode': 'Offline Mode',
    'profile.needHelp': 'Need Help?',
    'profile.contactSupport': 'Contact Support',
    'profile.userGuide': 'User Guide',
    'profile.saveChanges': 'Save Changes',
    
    // Emergency
    'emergency.title': 'Emergency',
    'emergency.medicalEmergency': 'Medical Emergency',
    'emergency.callForHelp': 'Call for immediate medical assistance',
    'emergency.callAmbulance': 'Call 108 - Ambulance',
    'emergency.emergencySymptoms': 'Emergency Symptoms',
    'emergency.emergencyContacts': 'Emergency Contacts',
    'emergency.nearbyHospitals': 'Nearby Hospitals',
    'emergency.firstAidTips': 'Quick First Aid Tips',
    'emergency.notEmergency': 'Not an emergency?',
    'emergency.high': 'High',
    'emergency.medium': 'Medium',
    'emergency.low': 'Low',
    
    // Pharmacy
    'pharmacy.title': 'Pharmacy Lookup',
    'pharmacy.searchMedicine': 'Search for medicine or generic name',
    'pharmacy.commonMedicines': 'Common Medicines',
    'pharmacy.availableAt': 'Available at:',
    'pharmacy.medicineNotFound': 'Medicine not found',
    'pharmacy.notAvailable': '"{query}" is not available at nearby pharmacies',
    'pharmacy.searchAlternatives': 'Search Alternative Medicines',
    'pharmacy.contactDoctor': 'Contact Doctor for Prescription',
    'pharmacy.available': 'Available',
    'pharmacy.outOfStock': 'Out of Stock',
    'pharmacy.callPharmacy': 'Call Pharmacy',
    'pharmacy.getDirections': 'Get Directions',
    'pharmacy.offlineMode': 'Offline Mode',
    'pharmacy.cachedInfo': 'This information is cached for offline access',
    'pharmacy.searching': 'Searching for medicines...',
    'pharmacy.lastUpdated': 'Last updated: {time} ago',
    'pharmacy.offlineModeAvailable': 'Offline Mode Available',
    
    // Medicines
    'medicines.title': 'Medicines',
    'medicines.searchPlaceholder': 'Search for medicines...',
    'medicines.categories.fever': 'Fever',
    'medicines.categories.cold': 'Cold',
    'medicines.categories.pain': 'Pain',
    'medicines.categories.all': 'All',
    'medicines.generic': 'Generic',
    'medicines.available': 'Available',
    'medicines.outOfStock': 'Out of Stock',
    'medicines.order': 'Order',
    'medicines.call': 'Call',
    'medicines.uploadPrescription': 'Upload Prescription',
    'medicines.uploadPrescriptionDescription': 'Get medicines delivered based on doctor\'s prescription',
    'medicines.upload': 'Upload',
    'medicines.aiAssistant': 'AI Assistant',
    'medicines.medicineAdvice': 'Medicine advice',
    'medicines.findPharmacy': 'Find Pharmacy',
    'medicines.nearbyStores': 'Nearby stores',
    
    // Records
    'records.title': 'Health Records',
    'records.online': 'Online',
    'records.offline': 'Offline Mode',
    'records.allSynced': 'All records are synced',
    'records.viewingCached': 'Viewing cached records. Changes will sync when online.',
    'records.allRecords': 'All Records',
    'records.consultations': 'Consultations',
    'records.labTests': 'Lab Tests',
    'records.prescriptions': 'Prescriptions',
    'records.vaccinations': 'Vaccinations',
    'records.addNewRecord': 'Add New Record',
    'records.uploadDocument': 'Upload Document',
    'records.addNote': 'Add Note',
    'records.sync': 'Sync',
    'records.offlineNotice': 'You are viewing cached records',
    
    // AI Chat
    'aiChat.title': 'Health AI',
    'aiChat.active': 'Active',
    'aiChat.enterMessage': 'Enter message',
    'aiChat.aiGenerated': 'AI generated, not a substitute to professional medical advice',
    'aiChat.quickActions': 'Quick Actions',
    'aiChat.checkFever': 'Check Fever',
    'aiChat.throatPain': 'Throat Pain',
    'aiChat.stomachPain': 'Stomach Pain',
    'aiChat.talkToDoctor': 'Talk to Doctor',
    
    // Video Consult
    'videoConsult.title': 'Video Consultation',
    'videoConsult.connecting': 'Connecting to Doctor...',
    'videoConsult.pleaseWait': 'Please wait while we connect you',
    'videoConsult.consultationDetails': 'Consultation Details',
    'videoConsult.duration': 'Duration',
    'videoConsult.fee': 'Fee',
    'videoConsult.available': 'Available',
    'videoConsult.yourConcerns': 'Your Concerns',
    'videoConsult.describeSymptoms': 'Describe your symptoms or health concerns...',
    'videoConsult.quickSymptoms': 'Quick Symptoms',
    'videoConsult.startConsultation': 'Start Video Consultation',
    'videoConsult.connectionIssues': 'Having connection issues?',
    'videoConsult.tryAI': 'Try AI Assistant (Free)',
    'videoConsult.switchVoice': 'Switch to Voice Call',
    'videoConsult.technicalRequirements': 'Technical Requirements',
    'videoConsult.callDuration': 'Call Duration',
    'videoConsult.endCall': 'End Call',
    
    // Book Appointment
    'bookAppointment.title': 'Book Appointment',
    'bookAppointment.consultationFor': 'Consultation for:',
    'bookAppointment.specialty': 'Specialty',
    'bookAppointment.appointmentType': 'Appointment Type',
    'bookAppointment.videoConsult': 'Video Consult',
    'bookAppointment.connectInstantly': 'Connect instantly',
    'bookAppointment.physicalVisit': 'Physical Visit',
    'bookAppointment.atHospital': 'At Hospital',
    'bookAppointment.availableDoctors': 'Available Doctors',
    'bookAppointment.selectDate': 'Select Date',
    'bookAppointment.selectTime': 'Select Time',
    'bookAppointment.bookAppointment': 'Book Appointment',
    'bookAppointment.needImmediateHelp': 'Need immediate help?',
    'bookAppointment.tryAI': 'Try AI Assistant (Free)',
    'bookAppointment.switchVoice': 'Switch to Voice Call',
    'bookAppointment.technicalRequirements': 'Technical Requirements'
  },
  hi: {
    // Home page
    'home.title': 'नाभा हेल्थ',
    'home.greeting': 'नमस्ते, राजेश कुमार',
    'home.physicalAppointment': 'भौतिक अपॉइंटमेंट',
    'home.atHospital': 'अस्पताल में',
    'home.videoConsult': 'वीडियो कंसल्ट',
    'home.connectIn5Sec': '5 सेकंड में कनेक्ट',
    'home.medicines': 'दवाएं',
    'home.pharmacyDelivery': 'फार्मेसी डिलीवरी',
    'home.labTests': 'लैब टेस्ट',
    'home.homeCollection': 'घर से नमूना लेना',
    'home.surgeries': 'सर्जरी',
    'home.bookProcedure': 'प्रक्रिया बुक करें',
    'home.findDoctor': 'अपनी स्वास्थ्य समस्या के लिए डॉक्टर खोजें',
    'home.generalPhysician': 'सामान्य चिकित्सक',
    'home.skinHair': 'त्वचा और बाल',
    'home.womensHealth': 'महिला स्वास्थ्य',
    'home.dentalCare': 'दंत चिकित्सा',
    'home.childSpecialist': 'बाल रोग विशेषज्ञ',
    'home.ent': 'कान, नाक, गला',
    'home.mentalWellness': 'मानसिक स्वास्थ्य',
    'home.more': '20+ और',
    'home.askHealthAI': 'हेल्थ AI से पूछें',
    'home.free': 'मुफ्त',
    'home.queriesResolved': 'पिछले महीने 20000+ स्वास्थ्य प्रश्नों का समाधान',
    'home.emergency': 'आपातकाल',
    'home.call108': '108 पर कॉल करें',
    'home.pharmacy': 'फार्मेसी',
    'home.checkAvailability': 'उपलब्धता जांचें',
    
    // Common
    'common.home': 'होम',
    'common.appointments': 'अपॉइंटमेंट',
    'common.records': 'रिकॉर्ड',
    'common.profile': 'प्रोफाइल',
    'common.search': 'खोजें',
    'common.book': 'बुक करें',
    'common.cancel': 'रद्द करें',
    'common.reschedule': 'पुनर्निर्धारित करें',
    'common.viewDetails': 'विवरण देखें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.confirm': 'पुष्टि करें',
    'common.back': 'वापस',
    'common.next': 'आगे',
    'common.previous': 'पिछला',
    'common.close': 'बंद करें',
    'common.save': 'सहेजें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.loading': 'लोड हो रहा है...',
    'common.logout': 'लॉगआउट',
    'common.quickActions': 'त्वरित क्रियाएं',
    'common.talkToAgent': 'एजेंट से बात करें',
    'common.videoConsult': 'वीडियो परामर्श',
    'common.callInProgress': 'कॉल प्रगति में',
    'common.connectingAgent': 'हेल्थकेयर एजेंट से जुड़ रहे हैं...',
    'common.consultationRecorded': 'आपकी परामर्श स्वचालित रूप से रिकॉर्ड होगी',
    'common.cancelCall': 'कॉल रद्द करें',
    'common.hello': 'नमस्ते',
    'common.user': 'उपयोगकर्ता',
    'common.baddiHimachal': 'बड्डी, हिमाचल',
    'common.sync': 'सिंक',
    'common.online': 'ऑनलाइन',
    'common.offline': 'ऑफलाइन',
    'common.allRecordsSynced': 'सभी रिकॉर्ड सिंक हो गए हैं',
    'common.loadingRecords': 'रिकॉर्ड लोड हो रहे हैं...',
    'common.noRecordsFound': 'कोई रिकॉर्ड नहीं मिला',
    'common.noHealthRecordsYet': 'आपके पास अभी तक कोई स्वास्थ्य रिकॉर्ड नहीं है',
    'common.noRecordsOfType': 'कोई {type} रिकॉर्ड नहीं',
    'common.viewAllDetails': 'सभी विवरण देखें',
    'common.active': 'सक्रिय',
    'common.scheduled': 'निर्धारित',
    'common.completed': 'पूर्ण',
    'common.video': 'वीडियो',
    'common.aiAssistant': 'AI सहायक',
    'common.addNewRecord': 'नया रिकॉर्ड जोड़ें',
    'common.uploadDocumentNote': 'दस्तावेज़ अपलोड करें, नोट्स जोड़ें, या नई स्वास्थ्य जानकारी रिकॉर्ड करें',
    'common.uploadDocument': '📄 दस्तावेज़ अपलोड करें',
    'common.addNote': '📝 नोट जोड़ें',
    'common.viewUpcoming': 'आगामी देखें',
    'common.checkAvailability': 'उपलब्धता जांचें',
    'common.category': 'श्रेणी',
    'common.offlineMode': 'ऑफलाइन मोड',
    'common.offlineModeDescription': 'आप कैश्ड रिकॉर्ड देख रहे हैं। नए रिकॉर्ड स्थानीय रूप से सहेजे जाएंगे और ऑनलाइन होने पर सिंक होंगे।',
    'common.consultation': 'परामर्श',
    'common.aiAnalysis': 'AI विश्लेषण',
    'common.prescription': 'पर्ची',
    'common.labTest': 'लैब टेस्ट',
    'common.vaccination': 'टीकाकरण',
    'common.patientReported': 'रोगी ने बुखार और गले में दर्द की शिकायत की और उन्हें ऑनलाइन डॉक्टर से परामर्श करने की सलाह दी गई।',
    'common.routineCheckup': 'नियमित स्वास्थ्य जांच, रक्तचाप सामान्य, वजन स्थिर',
    'common.bloodSugar': 'उपवास रक्त शर्करा: 95 mg/dL (सामान्य)',
    'common.medicationPrescribed': 'पैरासिटामोल 500mg - 3 दिनों के लिए दिन में 3 बार',
    'common.followUp': 'रक्तचाप की दवा के लिए फॉलो-अप',
    'common.noSummaryAvailable': 'कोई सारांश उपलब्ध नहीं',
    'common.consultationDescription': 'रोगी ने बुखार और गले में दर्द की शिकायत की और उन्हें ऑनलाइन डॉक्टर से परामर्श करने की सलाह दी गई।',
    'common.routineCheckupDescription': 'नियमित स्वास्थ्य जांच, रक्तचाप सामान्य, वजन स्थिर',
    'common.bloodSugarDescription': 'उपवास रक्त शर्करा: 95 mg/dL (सामान्य)',
    'common.medicationDescription': 'पैरासिटामोल 500mg - 3 दिनों के लिए दिन में 3 बार',
    'common.followUpDescription': 'रक्तचाप की दवा के लिए फॉलो-अप',
    'common.generalHealthCheckup': 'सामान्य स्वास्थ्य जांच',
    'common.bloodSugarTest': 'रक्त शर्करा परीक्षण',
    'common.medicationForFever': 'बुखार की दवा',
    'common.followUpAppointment': 'फॉलो-अप अपॉइंटमेंट',
    'common.callRegistered': 'कॉल पंजीकृत',
    'common.awaitingDoctorResponse': 'डॉक्टर की प्रतिक्रिया की प्रतीक्षा',
    'common.callCompleted': 'कॉल पूर्ण! आपकी परामर्श पंजीकृत हो गई है।',
    'common.agentCall': 'एजेंट कॉल',
    'common.callInProgress': 'कॉल प्रगति में',
    'common.connectingAgent': 'हेल्थकेयर एजेंट से जुड़ रहे हैं...',
    'common.consultationRecorded': 'आपकी परामर्श स्वचालित रूप से रिकॉर्ड होगी',
    'common.cancelCall': 'कॉल रद्द करें',
    
    // Appointments
    'appointments.title': 'अपॉइंटमेंट',
    'appointments.upcoming': 'आगामी',
    'appointments.completed': 'पूर्ण',
    'appointments.cancelled': 'रद्द',
    'appointments.all': 'सभी',
    'appointments.pending': 'लंबित',
    'appointments.confirmed': 'पुष्टि की गई',
    'appointments.noAppointments': 'कोई अपॉइंटमेंट नहीं',
    'appointments.noAppointmentsDescription': 'आपके पास अभी तक कोई अपॉइंटमेंट नहीं है',
    'appointments.bookNew': 'नया अपॉइंटमेंट बुक करें',
    'appointments.upcomingReminder': 'आगामी अपॉइंटमेंट',
    
    // Profile
    'profile.title': 'प्रोफाइल',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.medicalInfo': 'चिकित्सा जानकारी',
    'profile.fullName': 'पूरा नाम',
    'profile.age': 'आयु',
    'profile.phoneNumber': 'फोन नंबर',
    'profile.location': 'स्थान',
    'profile.bloodGroup': 'रक्त समूह',
    'profile.allergies': 'एलर्जी',
    'profile.medicalConditions': 'चिकित्सा स्थितियां',
    'profile.emergencyContact': 'आपातकालीन संपर्क',
    'profile.settings': 'सेटिंग्स',
    'profile.notifications': 'सूचनाएं',
    'profile.language': 'भाषा',
    'profile.privacySecurity': 'गोपनीयता और सुरक्षा',
    'profile.offlineMode': 'ऑफलाइन मोड',
    'profile.needHelp': 'मदद चाहिए?',
    'profile.contactSupport': 'सहायता से संपर्क करें',
    'profile.userGuide': 'उपयोगकर्ता गाइड',
    'profile.saveChanges': 'परिवर्तन सहेजें',
    
    // Emergency
    'emergency.title': 'आपातकाल',
    'emergency.medicalEmergency': 'चिकित्सा आपातकाल',
    'emergency.callForHelp': 'तत्काल चिकित्सा सहायता के लिए कॉल करें',
    'emergency.callAmbulance': '108 - एम्बुलेंस पर कॉल करें',
    'emergency.emergencySymptoms': 'आपातकालीन लक्षण',
    'emergency.emergencyContacts': 'आपातकालीन संपर्क',
    'emergency.nearbyHospitals': 'निकटतम अस्पताल',
    'emergency.firstAidTips': 'त्वरित प्राथमिक चिकित्सा सुझाव',
    'emergency.notEmergency': 'आपातकाल नहीं?',
    'emergency.high': 'उच्च',
    'emergency.medium': 'मध्यम',
    'emergency.low': 'निम्न',
    
    // Pharmacy
    'pharmacy.title': 'फार्मेसी खोज',
    'pharmacy.searchMedicine': 'दवा या जेनेरिक नाम खोजें',
    'pharmacy.commonMedicines': 'सामान्य दवाएं',
    'pharmacy.availableAt': 'उपलब्ध है:',
    'pharmacy.medicineNotFound': 'दवा नहीं मिली',
    'pharmacy.notAvailable': '"{query}" निकटवर्ती फार्मेसियों में उपलब्ध नहीं है',
    'pharmacy.searchAlternatives': 'वैकल्पिक दवाएं खोजें',
    'pharmacy.contactDoctor': 'पर्चे के लिए डॉक्टर से संपर्क करें',
    'pharmacy.available': 'उपलब्ध',
    'pharmacy.outOfStock': 'स्टॉक में नहीं',
    'pharmacy.callPharmacy': 'फार्मेसी को कॉल करें',
    'pharmacy.getDirections': 'दिशा-निर्देश प्राप्त करें',
    'pharmacy.offlineMode': 'ऑफलाइन मोड',
    'pharmacy.cachedInfo': 'यह जानकारी ऑफलाइन एक्सेस के लिए कैश की गई है',
    'pharmacy.searching': 'दवाओं की खोज हो रही है...',
    'pharmacy.lastUpdated': 'अंतिम अपडेट: {time} पहले',
    'pharmacy.offlineModeAvailable': 'ऑफलाइन मोड उपलब्ध',
    
    // Medicines
    'medicines.title': 'दवाएं',
    'medicines.searchPlaceholder': 'दवाओं की खोज करें...',
    'medicines.categories.fever': 'बुखार',
    'medicines.categories.cold': 'सर्दी',
    'medicines.categories.pain': 'दर्द',
    'medicines.categories.all': 'सभी',
    'medicines.generic': 'जेनेरिक',
    'medicines.available': 'उपलब्ध',
    'medicines.outOfStock': 'स्टॉक में नहीं',
    'medicines.order': 'ऑर्डर करें',
    'medicines.call': 'कॉल करें',
    'medicines.uploadPrescription': 'पर्चा अपलोड करें',
    'medicines.uploadPrescriptionDescription': 'डॉक्टर के पर्चे के आधार पर दवाएं डिलीवर करवाएं',
    'medicines.upload': 'अपलोड करें',
    'medicines.aiAssistant': 'AI असिस्टेंट',
    'medicines.medicineAdvice': 'दवा सलाह',
    'medicines.findPharmacy': 'फार्मेसी खोजें',
    'medicines.nearbyStores': 'निकटवर्ती स्टोर',
    
    // Records
    'records.title': 'स्वास्थ्य रिकॉर्ड',
    'records.online': 'ऑनलाइन',
    'records.offline': 'ऑफलाइन मोड',
    'records.allSynced': 'सभी रिकॉर्ड सिंक हो गए',
    'records.viewingCached': 'कैश किए गए रिकॉर्ड देख रहे हैं। ऑनलाइन होने पर परिवर्तन सिंक होंगे।',
    'records.allRecords': 'सभी रिकॉर्ड',
    'records.consultations': 'परामर्श',
    'records.labTests': 'लैब टेस्ट',
    'records.prescriptions': 'पर्चे',
    'records.vaccinations': 'टीकाकरण',
    'records.addNewRecord': 'नया रिकॉर्ड जोड़ें',
    'records.uploadDocument': 'दस्तावेज़ अपलोड करें',
    'records.addNote': 'नोट जोड़ें',
    'records.sync': 'सिंक',
    'records.offlineNotice': 'आप कैश किए गए रिकॉर्ड देख रहे हैं',
    
    // AI Chat
    'aiChat.title': 'हेल्थ AI',
    'aiChat.active': 'सक्रिय',
    'aiChat.enterMessage': 'संदेश दर्ज करें',
    'aiChat.aiGenerated': 'AI द्वारा उत्पन्न, पेशेवर चिकित्सा सलाह का विकल्प नहीं',
    'aiChat.quickActions': 'त्वरित क्रियाएं',
    'aiChat.checkFever': 'बुखार जांचें',
    'aiChat.throatPain': 'गले में दर्द',
    'aiChat.stomachPain': 'पेट दर्द',
    'aiChat.talkToDoctor': 'डॉक्टर से बात करें',
    
    // Video Consult
    'videoConsult.title': 'वीडियो परामर्श',
    'videoConsult.connecting': 'डॉक्टर से जुड़ रहे हैं...',
    'videoConsult.pleaseWait': 'कृपया प्रतीक्षा करें जब हम आपको जोड़ते हैं',
    'videoConsult.consultationDetails': 'परामर्श विवरण',
    'videoConsult.duration': 'अवधि',
    'videoConsult.fee': 'शुल्क',
    'videoConsult.available': 'उपलब्ध',
    'videoConsult.yourConcerns': 'आपकी चिंताएं',
    'videoConsult.describeSymptoms': 'अपने लक्षणों या स्वास्थ्य चिंताओं का वर्णन करें...',
    'videoConsult.quickSymptoms': 'त्वरित लक्षण',
    'videoConsult.startConsultation': 'वीडियो परामर्श शुरू करें',
    'videoConsult.connectionIssues': 'कनेक्शन की समस्या?',
    'videoConsult.tryAI': 'AI असिस्टेंट आजमाएं (मुफ्त)',
    'videoConsult.switchVoice': 'वॉयस कॉल पर स्विच करें',
    'videoConsult.technicalRequirements': 'तकनीकी आवश्यकताएं',
    'videoConsult.callDuration': 'कॉल अवधि',
    'videoConsult.endCall': 'कॉल समाप्त करें',
    
    // Book Appointment
    'bookAppointment.title': 'अपॉइंटमेंट बुक करें',
    'bookAppointment.consultationFor': 'परामर्श के लिए:',
    'bookAppointment.specialty': 'विशेषता',
    'bookAppointment.appointmentType': 'अपॉइंटमेंट प्रकार',
    'bookAppointment.videoConsult': 'वीडियो कंसल्ट',
    'bookAppointment.connectInstantly': 'तुरंत कनेक्ट करें',
    'bookAppointment.physicalVisit': 'भौतिक यात्रा',
    'bookAppointment.atHospital': 'अस्पताल में',
    'bookAppointment.availableDoctors': 'उपलब्ध डॉक्टर',
    'bookAppointment.selectDate': 'तारीख चुनें',
    'bookAppointment.selectTime': 'समय चुनें',
    'bookAppointment.bookAppointment': 'अपॉइंटमेंट बुक करें',
    'bookAppointment.needImmediateHelp': 'तत्काल मदद चाहिए?',
    'bookAppointment.tryAI': 'AI असिस्टेंट आजमाएं (मुफ्त)',
    'bookAppointment.switchVoice': 'वॉयस कॉल पर स्विच करें',
    'bookAppointment.technicalRequirements': 'तकनीकी आवश्यकताएं'
  },
  pa: {
    // Home page
    'home.title': 'ਨਾਭਾ ਹੈਲਥ',
    'home.greeting': 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਰਾਜੇਸ਼ ਕੁਮਾਰ',
    'home.physicalAppointment': 'ਭੌਤਿਕ ਮੁਲਾਕਾਤ',
    'home.atHospital': 'ਹਸਪਤਾਲ ਵਿੱਚ',
    'home.videoConsult': 'ਵੀਡੀਓ ਸਲਾਹ',
    'home.connectIn5Sec': '5 ਸਕਿੰਟ ਵਿੱਚ ਕਨੈਕਟ',
    'home.medicines': 'ਦਵਾਈਆਂ',
    'home.pharmacyDelivery': 'ਫਾਰਮੇਸੀ ਡਿਲੀਵਰੀ',
    'home.labTests': 'ਲੈਬ ਟੈਸਟ',
    'home.homeCollection': 'ਘਰੋਂ ਨਮੂਨਾ ਲੈਣਾ',
    'home.surgeries': 'ਸਰਜਰੀ',
    'home.bookProcedure': 'ਪ੍ਰਕਿਰਿਆ ਬੁੱਕ ਕਰੋ',
    'home.findDoctor': 'ਆਪਣੀ ਸਿਹਤ ਸਮਸਿਆ ਲਈ ਡਾਕਟਰ ਲੱਭੋ',
    'home.generalPhysician': 'ਆਮ ਡਾਕਟਰ',
    'home.skinHair': 'ਚਮੜੀ ਅਤੇ ਵਾਲ',
    'home.womensHealth': 'ਮਹਿਲਾ ਸਿਹਤ',
    'home.dentalCare': 'ਦੰਦਾਂ ਦੀ ਦੇਖਭਾਲ',
    'home.childSpecialist': 'ਬਾਲ ਰੋਗ ਵਿਸ਼ੇਸ਼ਜ',
    'home.ent': 'ਕੰਨ, ਨੱਕ, ਗਲਾ',
    'home.mentalWellness': 'ਮਾਨਸਿਕ ਸਿਹਤ',
    'home.more': '20+ ਹੋਰ',
    'home.askHealthAI': 'ਹੈਲਥ AI ਤੋਂ ਪੁੱਛੋ',
    'home.free': 'ਮੁਫਤ',
    'home.queriesResolved': 'ਪਿਛਲੇ ਮਹੀਨੇ 20000+ ਸਿਹਤ ਸਵਾਲਾਂ ਦਾ ਹੱਲ',
    'home.emergency': 'ਐਮਰਜੈਂਸੀ',
    'home.call108': '108 ਤੇ ਕਾਲ ਕਰੋ',
    'home.pharmacy': 'ਫਾਰਮੇਸੀ',
    'home.checkAvailability': 'ਉਪਲਬਧਤਾ ਜਾਂਚੋ',
    
    // Common
    'common.home': 'ਘਰ',
    'common.appointments': 'ਮੁਲਾਕਾਤਾਂ',
    'common.records': 'ਰਿਕਾਰਡ',
    'common.profile': 'ਪ੍ਰੋਫਾਈਲ',
    'common.search': 'ਖੋਜ',
    'common.book': 'ਬੁੱਕ ਕਰੋ',
    'common.cancel': 'ਰੱਦ ਕਰੋ',
    'common.reschedule': 'ਦੁਬਾਰਾ ਸਮਾਂ ਨਿਰਧਾਰਿਤ ਕਰੋ',
    'common.viewDetails': 'ਵਿਵਰਣ ਦੇਖੋ',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'common.error': 'ਗਲਤੀ',
    'common.success': 'ਸਫਲਤਾ',
    'common.confirm': 'ਪੁਸ਼ਟੀ ਕਰੋ',
    'common.back': 'ਵਾਪਸ',
    'common.next': 'ਅੱਗੇ',
    'common.previous': 'ਪਿਛਲਾ',
    'common.close': 'ਬੰਦ ਕਰੋ',
    'common.save': 'ਸੇਵ ਕਰੋ',
    'common.edit': 'ਸੰਪਾਦਨ ਕਰੋ',
    'common.delete': 'ਹਟਾਓ',
    'common.yes': 'ਹਾਂ',
    'common.no': 'ਨਹੀਂ',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'common.logout': 'ਲੌਗਆਉਟ',
    'common.quickActions': 'ਤੁਰੰਤ ਕਿਰਿਆਵਾਂ',
    'common.talkToAgent': 'ਏਜੰਟ ਨਾਲ ਗੱਲ ਕਰੋ',
    'common.videoConsult': 'ਵੀਡੀਓ ਸਲਾਹ',
    'common.callInProgress': 'ਕਾਲ ਚਲ ਰਿਹਾ ਹੈ',
    'common.connectingAgent': 'ਹੈਲਥਕੇਅਰ ਏਜੰਟ ਨਾਲ ਜੁੜ ਰਹੇ ਹਾਂ...',
    'common.consultationRecorded': 'ਤੁਹਾਡੀ ਸਲਾਹ ਆਪਣੇ ਆਪ ਰਿਕਾਰਡ ਹੋ ਜਾਵੇਗੀ',
    'common.cancelCall': 'ਕਾਲ ਰੱਦ ਕਰੋ',
    'common.hello': 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
    'common.user': 'ਯੂਜਰ',
    'common.baddiHimachal': 'ਬੱਡੀ, ਹਿਮਾਚਲ',
    'common.sync': 'ਸਿੰਕ',
    'common.online': 'ਔਨਲਾਈਨ',
    'common.offline': 'ਔਫਲਾਈਨ',
    'common.allRecordsSynced': 'ਸਾਰੇ ਰਿਕਾਰਡ ਸਿੰਕ ਹੋ ਗਏ ਹਨ',
    'common.loadingRecords': 'ਰਿਕਾਰਡ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...',
    'common.noRecordsFound': 'ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ',
    'common.noHealthRecordsYet': 'ਤੁਹਾਡੇ ਕੋਲ ਅਜੇ ਤੱਕ ਕੋਈ ਸਿਹਤ ਰਿਕਾਰਡ ਨਹੀਂ ਹੈ',
    'common.noRecordsOfType': 'ਕੋਈ {type} ਰਿਕਾਰਡ ਨਹੀਂ',
    'common.viewAllDetails': 'ਸਾਰੇ ਵਿਵਰਣ ਦੇਖੋ',
    'common.active': 'ਸਰਗਰਮ',
    'common.scheduled': 'ਨਿਰਧਾਰਿਤ',
    'common.completed': 'ਪੂਰਾ',
    'common.video': 'ਵੀਡੀਓ',
    'common.aiAssistant': 'AI ਸਹਾਇਕ',
    'common.addNewRecord': 'ਨਵਾਂ ਰਿਕਾਰਡ ਜੋੜੋ',
    'common.uploadDocumentNote': 'ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ, ਨੋਟਸ ਜੋੜੋ, ਜਾਂ ਨਵੀਂ ਸਿਹਤ ਜਾਣਕਾਰੀ ਰਿਕਾਰਡ ਕਰੋ',
    'common.uploadDocument': '📄 ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ',
    'common.addNote': '📝 ਨੋਟ ਜੋੜੋ',
    'common.viewUpcoming': 'ਆਉਣ ਵਾਲੇ ਦੇਖੋ',
    'common.checkAvailability': 'ਉਪਲਬਧਤਾ ਜਾਂਚੋ',
    'common.category': 'ਸ਼੍ਰੇਣੀ',
    'common.offlineMode': 'ਔਫਲਾਈਨ ਮੋਡ',
    'common.offlineModeDescription': 'ਤੁਸੀਂ ਕੈਸ਼ਡ ਰਿਕਾਰਡ ਦੇਖ ਰਹੇ ਹੋ। ਨਵੇਂ ਰਿਕਾਰਡ ਸਥਾਨਕ ਤੌਰ \'ਤੇ ਸੇਵ ਕੀਤੇ ਜਾਣਗੇ ਅਤੇ ਔਨਲਾਈਨ ਹੋਣ \'ਤੇ ਸਿੰਕ ਹੋਣਗੇ।',
    'common.consultation': 'ਸਲਾਹ',
    'common.aiAnalysis': 'AI ਵਿਸ਼ਲੇਸ਼ਣ',
    'common.prescription': 'ਦਵਾਈ ਦਾ ਪਰਸਕ੍ਰਿਪਸ਼ਨ',
    'common.labTest': 'ਲੈਬ ਟੈਸਟ',
    'common.vaccination': 'ਟੀਕਾਕਰਣ',
    'common.patientReported': 'ਮਰੀਜ਼ ਨੇ ਬੁਖਾਰ ਅਤੇ ਗਲੇ ਦੇ ਦਰਦ ਦੀ ਸ਼ਿਕਾਇਤ ਕੀਤੀ ਅਤੇ ਉਨ੍ਹਾਂ ਨੂੰ ਔਨਲਾਈਨ ਡਾਕਟਰ ਤੋਂ ਸਲਾਹ ਲੈਣ ਦੀ ਸਲਾਹ ਦਿੱਤੀ ਗਈ।',
    'common.routineCheckup': 'ਰੁਟੀਨ ਸਿਹਤ ਜਾਂਚ, ਖੂਨ ਦਾ ਦਬਾਅ ਸਾਧਾਰਣ, ਵਜ਼ਨ ਸਥਿਰ',
    'common.bloodSugar': 'ਉਪਵਾਸ ਖੂਨ ਦੀ ਸ਼ੱਕਰ: 95 mg/dL (ਸਾਧਾਰਣ)',
    'common.medicationPrescribed': 'ਪੈਰਾਸੀਟਾਮੋਲ 500mg - 3 ਦਿਨਾਂ ਲਈ ਦਿਨ ਵਿੱਚ 3 ਵਾਰ',
    'common.followUp': 'ਖੂਨ ਦੇ ਦਬਾਅ ਦੀ ਦਵਾਈ ਲਈ ਫਾਲੋ-ਅਪ',
    'common.noSummaryAvailable': 'ਕੋਈ ਸਾਰਾਂਸ਼ ਉਪਲਬਧ ਨਹੀਂ',
    'common.consultationDescription': 'ਮਰੀਜ਼ ਨੇ ਬੁਖਾਰ ਅਤੇ ਗਲੇ ਦੇ ਦਰਦ ਦੀ ਸ਼ਿਕਾਇਤ ਕੀਤੀ ਅਤੇ ਉਨ੍ਹਾਂ ਨੂੰ ਔਨਲਾਈਨ ਡਾਕਟਰ ਤੋਂ ਸਲਾਹ ਲੈਣ ਦੀ ਸਲਾਹ ਦਿੱਤੀ ਗਈ।',
    'common.routineCheckupDescription': 'ਰੁਟੀਨ ਸਿਹਤ ਜਾਂਚ, ਖੂਨ ਦਾ ਦਬਾਅ ਸਾਧਾਰਣ, ਵਜ਼ਨ ਸਥਿਰ',
    'common.bloodSugarDescription': 'ਉਪਵਾਸ ਖੂਨ ਦੀ ਸ਼ੱਕਰ: 95 mg/dL (ਸਾਧਾਰਣ)',
    'common.medicationDescription': 'ਪੈਰਾਸੀਟਾਮੋਲ 500mg - 3 ਦਿਨਾਂ ਲਈ ਦਿਨ ਵਿੱਚ 3 ਵਾਰ',
    'common.followUpDescription': 'ਖੂਨ ਦੇ ਦਬਾਅ ਦੀ ਦਵਾਈ ਲਈ ਫਾਲੋ-ਅਪ',
    'common.generalHealthCheckup': 'ਆਮ ਸਿਹਤ ਜਾਂਚ',
    'common.bloodSugarTest': 'ਖੂਨ ਦੀ ਸ਼ੱਕਰ ਟੈਸਟ',
    'common.medicationForFever': 'ਬੁਖਾਰ ਦੀ ਦਵਾਈ',
    'common.followUpAppointment': 'ਫਾਲੋ-ਅਪ ਮੁਲਾਕਾਤ',
    'common.callRegistered': 'ਕਾਲ ਰਜਿਸਟਰਡ',
    'common.awaitingDoctorResponse': 'ਡਾਕਟਰ ਦੀ ਪ੍ਰਤਿਕਿਰਿਆ ਦੀ ਉਡੀਕ',
    'common.callCompleted': 'ਕਾਲ ਪੂਰਾ! ਤੁਹਾਡੀ ਸਲਾਹ ਰਜਿਸਟਰ ਹੋ ਗਈ ਹੈ।',
    'common.agentCall': 'ਏਜੰਟ ਕਾਲ',
    'common.callInProgress': 'ਕਾਲ ਚਲ ਰਿਹਾ ਹੈ',
    'common.connectingAgent': 'ਹੈਲਥਕੇਅਰ ਏਜੰਟ ਨਾਲ ਜੁੜ ਰਹੇ ਹਾਂ...',
    'common.consultationRecorded': 'ਤੁਹਾਡੀ ਸਲਾਹ ਆਪਣੇ ਆਪ ਰਿਕਾਰਡ ਹੋ ਜਾਵੇਗੀ',
    'common.cancelCall': 'ਕਾਲ ਰੱਦ ਕਰੋ',
    
    // Appointments
    'appointments.title': 'ਮੁਲਾਕਾਤਾਂ',
    'appointments.upcoming': 'ਆਉਣ ਵਾਲੀਆਂ',
    'appointments.completed': 'ਪੂਰੀਆਂ',
    'appointments.cancelled': 'ਰੱਦ',
    'appointments.all': 'ਸਭ',
    'appointments.pending': 'ਲੰਬਿਤ',
    'appointments.confirmed': 'ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ',
    'appointments.noAppointments': 'ਕੋਈ ਮੁਲਾਕਾਤ ਨਹੀਂ',
    'appointments.noAppointmentsDescription': 'ਤੁਹਾਡੇ ਕੋਲ ਅਜੇ ਤੱਕ ਕੋਈ ਮੁਲਾਕਾਤ ਨਹੀਂ ਹੈ',
    'appointments.bookNew': 'ਨਵੀਂ ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ',
    'appointments.upcomingReminder': 'ਆਉਣ ਵਾਲੀ ਮੁਲਾਕਾਤ',
    
    // Profile
    'profile.title': 'ਪ੍ਰੋਫਾਈਲ',
    'profile.personalInfo': 'ਨਿੱਜੀ ਜਾਣਕਾਰੀ',
    'profile.medicalInfo': 'ਡਾਕਟਰੀ ਜਾਣਕਾਰੀ',
    'profile.fullName': 'ਪੂਰਾ ਨਾਮ',
    'profile.age': 'ਉਮਰ',
    'profile.phoneNumber': 'ਫੋਨ ਨੰਬਰ',
    'profile.location': 'ਟਿਕਾਣਾ',
    'profile.bloodGroup': 'ਖੂਨ ਦਾ ਗਰੁੱਪ',
    'profile.allergies': 'ਐਲਰਜੀ',
    'profile.medicalConditions': 'ਡਾਕਟਰੀ ਹਾਲਤਾਂ',
    'profile.emergencyContact': 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
    'profile.settings': 'ਸੈਟਿੰਗਾਂ',
    'profile.notifications': 'ਸੂਚਨਾਵਾਂ',
    'profile.language': 'ਭਾਸ਼ਾ',
    'profile.privacySecurity': 'ਗੁਪਤਤਾ ਅਤੇ ਸੁਰੱਖਿਆ',
    'profile.offlineMode': 'ਆਫਲਾਈਨ ਮੋਡ',
    'profile.needHelp': 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    'profile.contactSupport': 'ਸਹਾਇਤਾ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
    'profile.userGuide': 'ਯੂਜਰ ਗਾਈਡ',
    'profile.saveChanges': 'ਬਦਲਾਅ ਸੇਵ ਕਰੋ',
    
    // Emergency
    'emergency.title': 'ਐਮਰਜੈਂਸੀ',
    'emergency.medicalEmergency': 'ਡਾਕਟਰੀ ਐਮਰਜੈਂਸੀ',
    'emergency.callForHelp': 'ਤੁਰੰਤ ਡਾਕਟਰੀ ਸਹਾਇਤਾ ਲਈ ਕਾਲ ਕਰੋ',
    'emergency.callAmbulance': '108 - ਐਂਬੂਲੈਂਸ ਤੇ ਕਾਲ ਕਰੋ',
    'emergency.emergencySymptoms': 'ਐਮਰਜੈਂਸੀ ਲੱਛਣ',
    'emergency.emergencyContacts': 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
    'emergency.nearbyHospitals': 'ਨਜ਼ਦੀਕੀ ਹਸਪਤਾਲ',
    'emergency.firstAidTips': 'ਤੁਰੰਤ ਪਹਿਲੀ ਸਹਾਇਤਾ ਸੁਝਾਅ',
    'emergency.notEmergency': 'ਐਮਰਜੈਂਸੀ ਨਹੀਂ?',
    'emergency.high': 'ਉੱਚ',
    'emergency.medium': 'ਮੱਧਮ',
    'emergency.low': 'ਘੱਟ',
    
    // Pharmacy
    'pharmacy.title': 'ਫਾਰਮੇਸੀ ਖੋਜ',
    'pharmacy.searchMedicine': 'ਦਵਾਈ ਜਾਂ ਜੇਨਰਿਕ ਨਾਮ ਖੋਜੋ',
    'pharmacy.commonMedicines': 'ਆਮ ਦਵਾਈਆਂ',
    'pharmacy.availableAt': 'ਉਪਲਬਧ ਹੈ:',
    'pharmacy.medicineNotFound': 'ਦਵਾਈ ਨਹੀਂ ਮਿਲੀ',
    'pharmacy.notAvailable': '"{query}" ਨਜ਼ਦੀਕੀ ਫਾਰਮੇਸੀਆਂ ਵਿੱਚ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
    'pharmacy.searchAlternatives': 'ਵਿਕਲਪਿਕ ਦਵਾਈਆਂ ਖੋਜੋ',
    'pharmacy.contactDoctor': 'ਪ੍ਰੈਸਕ੍ਰਿਪਸ਼ਨ ਲਈ ਡਾਕਟਰ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
    'pharmacy.available': 'ਉਪਲਬਧ',
    'pharmacy.outOfStock': 'ਸਟਾਕ ਵਿੱਚ ਨਹੀਂ',
    'pharmacy.callPharmacy': 'ਫਾਰਮੇਸੀ ਨੂੰ ਕਾਲ ਕਰੋ',
    'pharmacy.getDirections': 'ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ',
    'pharmacy.offlineMode': 'ਆਫਲਾਈਨ ਮੋਡ',
    'pharmacy.cachedInfo': 'ਇਹ ਜਾਣਕਾਰੀ ਆਫਲਾਈਨ ਐਕਸੈਸ ਲਈ ਕੈਸ਼ ਕੀਤੀ ਗਈ ਹੈ',
    'pharmacy.searching': 'ਦਵਾਈਆਂ ਖੋਜ ਰਹੇ ਹਾਂ...',
    'pharmacy.lastUpdated': 'ਆਖਰੀ ਅਪਡੇਟ: {time} ਪਹਿਲਾਂ',
    'pharmacy.offlineModeAvailable': 'ਆਫਲਾਈਨ ਮੋਡ ਉਪਲਬਧ',
    
    // Medicines
    'medicines.title': 'ਦਵਾਈਆਂ',
    'medicines.searchPlaceholder': 'ਦਵਾਈਆਂ ਖੋਜੋ...',
    'medicines.categories.fever': 'ਬੁਖਾਰ',
    'medicines.categories.cold': 'ਜ਼ੁਕਾਮ',
    'medicines.categories.pain': 'ਦਰਦ',
    'medicines.categories.all': 'ਸਭ',
    'medicines.generic': 'ਜੇਨਰਿਕ',
    'medicines.available': 'ਉਪਲਬਧ',
    'medicines.outOfStock': 'ਸਟਾਕ ਵਿੱਚ ਨਹੀਂ',
    'medicines.order': 'ਆਰਡਰ ਕਰੋ',
    'medicines.call': 'ਕਾਲ ਕਰੋ',
    'medicines.uploadPrescription': 'ਪ੍ਰੈਸਕ੍ਰਿਪਸ਼ਨ ਅਪਲੋਡ ਕਰੋ',
    'medicines.uploadPrescriptionDescription': 'ਡਾਕਟਰ ਦੇ ਪ੍ਰੈਸਕ੍ਰਿਪਸ਼ਨ ਦੇ ਆਧਾਰ \'ਤੇ ਦਵਾਈਆਂ ਡਿਲੀਵਰ ਕਰਵਾਓ',
    'medicines.upload': 'ਅਪਲੋਡ ਕਰੋ',
    'medicines.aiAssistant': 'AI ਅਸਿਸਟੈਂਟ',
    'medicines.medicineAdvice': 'ਦਵਾਈ ਸਲਾਹ',
    'medicines.findPharmacy': 'ਫਾਰਮੇਸੀ ਖੋਜੋ',
    'medicines.nearbyStores': 'ਨਜ਼ਦੀਕੀ ਸਟੋਰ',
    
    // Records
    'records.title': 'ਸਿਹਤ ਰਿਕਾਰਡ',
    'records.online': 'ਆਨਲਾਈਨ',
    'records.offline': 'ਆਫਲਾਈਨ ਮੋਡ',
    'records.allSynced': 'ਸਭ ਰਿਕਾਰਡ ਸਿੰਕ ਹੋ ਗਏ',
    'records.viewingCached': 'ਕੈਸ਼ ਕੀਤੇ ਰਿਕਾਰਡ ਦੇਖ ਰਹੇ ਹੋ। ਆਨਲਾਈਨ ਹੋਣ ਤੇ ਬਦਲਾਅ ਸਿੰਕ ਹੋਣਗੇ।',
    'records.allRecords': 'ਸਭ ਰਿਕਾਰਡ',
    'records.consultations': 'ਸਲਾਹ',
    'records.labTests': 'ਲੈਬ ਟੈਸਟ',
    'records.prescriptions': 'ਪ੍ਰੈਸਕ੍ਰਿਪਸ਼ਨ',
    'records.vaccinations': 'ਟੀਕਾਕਰਣ',
    'records.addNewRecord': 'ਨਵਾਂ ਰਿਕਾਰਡ ਜੋੜੋ',
    'records.uploadDocument': 'ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ',
    'records.addNote': 'ਨੋਟ ਜੋੜੋ',
    'records.sync': 'ਸਿੰਕ',
    'records.offlineNotice': 'ਤੁਸੀਂ ਕੈਸ਼ ਕੀਤੇ ਰਿਕਾਰਡ ਦੇਖ ਰਹੇ ਹੋ',
    
    // AI Chat
    'aiChat.title': 'ਹੈਲਥ AI',
    'aiChat.active': 'ਸਰਗਰਮ',
    'aiChat.enterMessage': 'ਸੁਨੇਹਾ ਦਰਜ ਕਰੋ',
    'aiChat.aiGenerated': 'AI ਦੁਆਰਾ ਤਿਆਰ, ਪੇਸ਼ੇਵਰ ਡਾਕਟਰੀ ਸਲਾਹ ਦਾ ਵਿਕਲਪ ਨਹੀਂ',
    'aiChat.quickActions': 'ਤੁਰੰਤ ਕਿਰਿਆਵਾਂ',
    'aiChat.checkFever': 'ਬੁਖਾਰ ਜਾਂਚੋ',
    'aiChat.throatPain': 'ਗਲੇ ਵਿੱਚ ਦਰਦ',
    'aiChat.stomachPain': 'ਪੇਟ ਦਰਦ',
    'aiChat.talkToDoctor': 'ਡਾਕਟਰ ਨਾਲ ਗੱਲ ਕਰੋ',
    
    // Video Consult
    'videoConsult.title': 'ਵੀਡੀਓ ਸਲਾਹ',
    'videoConsult.connecting': 'ਡਾਕਟਰ ਨਾਲ ਜੁੜ ਰਹੇ ਹਾਂ...',
    'videoConsult.pleaseWait': 'ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ ਜਦੋਂ ਅਸੀਂ ਤੁਹਾਨੂੰ ਜੋੜਦੇ ਹਾਂ',
    'videoConsult.consultationDetails': 'ਸਲਾਹ ਵਿਵਰਣ',
    'videoConsult.duration': 'ਮਿਆਦ',
    'videoConsult.fee': 'ਫੀਸ',
    'videoConsult.available': 'ਉਪਲਬਧ',
    'videoConsult.yourConcerns': 'ਤੁਹਾਡੀਆਂ ਚਿੰਤਾਵਾਂ',
    'videoConsult.describeSymptoms': 'ਆਪਣੇ ਲੱਛਣਾਂ ਜਾਂ ਸਿਹਤ ਚਿੰਤਾਵਾਂ ਦਾ ਵਰਣਨ ਕਰੋ...',
    'videoConsult.quickSymptoms': 'ਤੁਰੰਤ ਲੱਛਣ',
    'videoConsult.startConsultation': 'ਵੀਡੀਓ ਸਲਾਹ ਸ਼ੁਰੂ ਕਰੋ',
    'videoConsult.connectionIssues': 'ਕਨੈਕਸ਼ਨ ਦੀ ਸਮਸਿਆ?',
    'videoConsult.tryAI': 'AI ਅਸਿਸਟੈਂਟ ਅਜ਼ਮਾਓ (ਮੁਫਤ)',
    'videoConsult.switchVoice': 'ਵੌਇਸ ਕਾਲ ਤੇ ਸਵਿਚ ਕਰੋ',
    'videoConsult.technicalRequirements': 'ਤਕਨੀਕੀ ਲੋੜਾਂ',
    'videoConsult.callDuration': 'ਕਾਲ ਮਿਆਦ',
    'videoConsult.endCall': 'ਕਾਲ ਖਤਮ ਕਰੋ',
    
    // Book Appointment
    'bookAppointment.title': 'ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ',
    'bookAppointment.consultationFor': 'ਸਲਾਹ ਲਈ:',
    'bookAppointment.specialty': 'ਵਿਸ਼ੇਸ਼ਤਾ',
    'bookAppointment.appointmentType': 'ਮੁਲਾਕਾਤ ਕਿਸਮ',
    'bookAppointment.videoConsult': 'ਵੀਡੀਓ ਸਲਾਹ',
    'bookAppointment.connectInstantly': 'ਤੁਰੰਤ ਕਨੈਕਟ ਕਰੋ',
    'bookAppointment.physicalVisit': 'ਭੌਤਿਕ ਯਾਤਰਾ',
    'bookAppointment.atHospital': 'ਹਸਪਤਾਲ ਵਿੱਚ',
    'bookAppointment.availableDoctors': 'ਉਪਲਬਧ ਡਾਕਟਰ',
    'bookAppointment.selectDate': 'ਤਾਰੀਖ ਚੁਣੋ',
    'bookAppointment.selectTime': 'ਸਮਾਂ ਚੁਣੋ',
    'bookAppointment.bookAppointment': 'ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ',
    'bookAppointment.needImmediateHelp': 'ਤੁਰੰਤ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    'bookAppointment.tryAI': 'AI ਅਸਿਸਟੈਂਟ ਅਜ਼ਮਾਓ (ਮੁਫਤ)',
    'bookAppointment.switchVoice': 'ਵੌਇਸ ਕਾਲ ਤੇ ਸਵਿਚ ਕਰੋ',
    'bookAppointment.technicalRequirements': 'ਤਕਨੀਕੀ ਲੋੜਾਂ'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('hi'); // Default to Hindi for rural Punjab

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const cycleLanguage = () => {
    const languages: Language[] = ['en', 'hi', 'pa'];
    const currentIndex = languages.indexOf(language);
    const nextIndex = (currentIndex + 1) % languages.length;
    setLanguage(languages[nextIndex]);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, cycleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}



